### ISSUE TITLE
RFE: debounce - allow manual debouncing

### ISSUE THREAD

**Issue by rplevka** [jpdias/node-red-contrib-self-healing#12]
It would be useful if I could cancel the already triggered bounce interval - e.g. by having a special attribute in the input message.

**Comment by jpdias** [comment]
@rplevka could you check if PR #15 works as a solution for you?

**Comment by rplevka** [comment]
@jpdias hi, sorry for a late reply:
I don't have a testing environment handy, but looking at the code, it looks good to me (logic-wise)
